version: "3.9"

services:
  go-server:
    build: .
    container_name: go-server
    ports:
      - "8000:8000"
    restart: unless-stopped
    networks:
      - go-net
    # Запускается в фоне при использовании docker compose up -d

networks:
  go-net:
    driver: bridge

